### ISSUE TITLE
SHREC17 dataset

### ISSUE THREAD

**Issue by QienJane** [NaturalStupldity/DD-Net#1]
Hello, the official website "http://www-rech.telecom-lille.fr/shrec2017-hand/" for downloading the SHREC17 dataset is no longer accessible.
Can you provide me with the following files from the SHREC17 dataset? If you can provide them, it would be a great help to my research.
Specifically, include:
The "general folder" that contains the folders "gesture_1" to "gesture_14".
This "general folder" contains the following files:
+---gesture_1 
| +---finger_1 
| | +---subject_1 
| | | +---essai_1 
| | | | | |   
| | | | depth_0.png 
| | | | depth_1.png 
| | | | | | | | ... 
| | | | depth_N-1.png 
| | | | general_informations.txt 
| | | skeletons_image.txt 
| | | skeletons_world.txt 
| | | | | | 
| | | \---essai_2 
| | | ... 
| | \---essai_5 
| \---subject_2 
| ... 
| \---subject_20 
| \---finger_2 
... 
\---gesture_14

**Comment by NaturalStupidlty** [comment]
Hello! 😊
You can find the full dataset available [here](https://shapenet.cs.stanford.edu/shrec17/)
If this website would be down for some reason, check out this[ mirror on Kaggle](https://www.kaggle.com/datasets/bartvbl/shrec-2017-dataset-mirror)
Hope this helps you, friend.
Good luck with your research!

And by the way, if you like my implementation, don't forget to give it a star! 💫

**Comment by QienJane** [comment]
Hello, I visited the https://shapenet.cs.stanford.edu/shrec17/, https://www.kaggle.com/datasets/bartvbl/shrec-2017-dataset-mirror and https://github.com/fandulu/DDNet/blob/master/SHREC/SHREC_data_preprocessing.ipynb URLs you gave me.

The first two URLs are the raw data in .obj format and the third URL is the code for processing the SHREC2017 dataset.

However, none of these three URLs provide the data in the folders "gesture_1" to "gesture_14" (depth_0.png, depth_1.png.... . depth_N-1.png, general_informations.txt, skeletons_image.txt, skeletons_world.txt, etc.).


I'd appreciate it if you could share this data with me!
