### ISSUE TITLE
Python environment

### ISSUE THREAD

**Issue by QienJane** [NaturalStupldity/DD-Net#2]
Hello, this is what you wrote in sources/utils.py:

import pickle
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import scipy.ndimage.interpolation as inter

from tqdm import tqdm
from tensorflow import Tensor
from scipy.signal import medfilt
from scipy.spatial.distance import cdist
from sklearn.metrics import confusion_matrix
from keras.src.layers import Lambda, Reshape
from keras.src.callbacks import History

But when I run it I get the following error:
ModuleNotFoundError: No module named 'keras.src'
Which version of keras are you using?
If it's easier, can you tell me the version of each library in your python environment?

**Comment by NaturalStupidlty** [comment]
Oh, sorry, I have just noticed that the project requirements have not been pushed to remote 🙄

The `keras==2.13.1`  has worked fine for me with my MacOS 12.7.2.

For other details about packages version you can refer to `requirements.txt`

**Comment by QienJane** [comment]
/Aha, thank you very much!
I've solved the environment problem yesterday, and the environment for the program was configured yesterday. I put in sources/utils.py:
from keras.src.layers import Lambda, Reshape
from keras.src.callbacks import History

Changed to the following:
from tensorflow.keras.layers import Lambda, Reshape
from tensorflow.keras.callbacks import History

Also, I downloaded the SHREC17 dataset from the two links you provided, but the data in both folders are raw files in .obj format. I did not find the folders "gesture_1" to "gesture_14".
The gesture_1 folder has: gesture_1/finger_1/subject_2/essai_1/skeletons_image.txt
So, I would like to ask you, is it possible to provide the folder "gesture_1" to "gesture_14" directly? I'd appreciate it if you could.

I would like to discuss further with you about the SHREC17 dataset, or anything about this gesture recognition research direction.
Can I ask you what communication software you usually use? What is the contact information?

**Comment by NaturalStupidlty** [comment]
Oh, I see,
To preprocess the data and get separate gestures in format like `gesture_1/finger_1/subject_2/essai_1/skeletons_image.txt` you can refer to the preprocessing pipeline from the original implementation of DDNet:
https://github.com/fandulu/DD-Net/blob/master/SHREC/SHREC_data_preprocessing.ipynb

If you have any more questions about this project of mine you can email me at olkhovatyi@knu.ua, but still I may be slow to respond sometimes

**Comment by QienJane** [comment]
Hi, I'm getting a lot of errors when I follow the requirements.txt to install the environment.
Some python and TensorFlow versions appear incompatible.
May I ask what exactly is your version of TensorFlow and python?

**Comment by NaturalStupidlty** [comment]
> Hi, I'm getting a lot of errors when I follow the requirements.txt to install the environment. Some python and TensorFlow versions appear incompatible. May I ask what exactly is your version of TensorFlow and python?

`python=3.11` has been used for this project. Mainly, because I also use recent versions of keras to utilize all its capabilities.
